fieldLayouts:
  e1252a16-8cda-4843-8c71-89bcce2f07d5:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-17T07:28:22+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\TitleField
            uid: 21bbb585-3f62-40ae-9801-3f5d6af19411
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: d71b22b6-6b7a-47c0-a07c-3d989c8e63f9
        userCondition: null
handle: site
name: Site
