color: null
fieldLayouts:
  5e526461-7cf5-45b0-95b9-d59fca7a86cb:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-10T07:34:39+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 27f911d1-c7b2-4506-8bdd-c66e8da1c89d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T07:39:01+00:00'
            elementCondition: null
            fieldUid: d4b38100-422d-40f1-8451-8f2b3fa83a8f
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 37a42c82-00f6-497d-acb5-9389a1eecb83
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T07:54:54+00:00'
            elementCondition: null
            fieldUid: 32002598-7728-4547-8fa7-171d7951c7f5
            handle: null
            includeInCards: false
            instructions: null
            label: Vragen
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7c4e2121-7c10-41f0-bc41-9b56addfd993
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 2feb2344-669d-46d1-a4d8-92548062f584
        userCondition: null
handle: faqGroup
hasTitleField: true
icon: table-list
name: 'FAQ Categorie'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
