color: null
fieldLayouts:
  d70cd5c7-3b21-497b-aec5-cb1ab7986bd2:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-10T07:43:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: Vraag
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3cc4ee1c-10db-4519-b5da-4e65812d9fc2
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-10T07:45:37+00:00'
            elementCondition: null
            fieldUid: bdadc13b-5397-44dc-9d8b-7f74bc739f86
            handle: answer
            includeInCards: false
            instructions: null
            label: Antwoord
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d5ea52be-816b-4f8f-a079-97a6d2dbbc9c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T12:51:54+00:00'
            elementCondition: null
            fieldUid: 44934f81-7401-4a11-85a1-d608b42326a9
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: cbb5badb-e4b9-44cb-a0c6-c0e25fb27f55
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1aa74853-6300-4e34-905c-ef896122c477
        userCondition: null
handle: faqItem
hasTitleField: true
icon: list-ol
name: 'FAQ item'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: language
