color: null
fieldLayouts:
  c070b18c-9adf-474a-a3d0-795a20fddd0c:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-15T11:52:26+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3e0d8cda-cf9f-4c2a-b05a-7ef9d4e637cc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-04-15T11:54:30+00:00'
            elementCondition: null
            fieldUid: 26a15df5-a4d1-4e6d-a0ba-af582206462c
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 10ddaaea-9f1d-4a61-a198-907700f6f95d
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: a44ed6cb-4c5c-41d8-b4ae-3fc3b8569943
        userCondition: null
handle: NAVIGATION_ITEM
hasTitleField: true
icon: sign-post
name: 'Navigation Item'
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
