color: null
fieldLayouts:
  4338d56f-6725-4073-9a80-bcb246c47834:
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-06-12T07:51:42+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 403eda1b-e775-437d-84f6-4d6d53d6ca7d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-06-12T07:57:09+00:00'
            elementCondition: null
            fieldUid: ea93d46f-8749-4505-b97a-5be1e9a05da9
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 21bc5521-0126-4e15-b472-1dd25f919e7b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-18T06:52:49+00:00'
            elementCondition: null
            fieldUid: 2ac5993a-d09d-4e89-9d5b-d2981c122ebb
            handle: asColumns
            includeInCards: false
            instructions: null
            label: 'Show as columns'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a04bf3e4-f961-4c9c-991e-670b47244e40
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 9608eb5e-396a-4297-b293-ea17c91e4d74
        userCondition: null
handle: tabItemChart
hasTitleField: true
icon: null
name: 'Tab item voor Grafiek '
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
