color: null
description: null
fieldLayouts:
  175ba44e-1b36-4424-bda7-a4631b383391:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-22T14:21:51+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3f00c5e2-3b3e-4300-a26f-4796dec06de8
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T14:23:49+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: bdadc13b-5397-44dc-9d8b-7f74bc739f86
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ae4de8ec-f333-4f70-9a64-7aaff264d4e8
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: 3327b956-254e-47ad-ae73-4089432f34b2
        userCondition: null
handle: tooltip
hasTitleField: true
icon: comment-dots
name: Tooltip
showSlugField: false
showStatusField: false
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
