altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  7b0b31a1-285d-4f3c-9644-5455b5c5a1a3:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-04-14T08:25:59+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: 4f9c32f7-be6f-4d43-b38a-ce270a705f38
            userCondition: null
            warning: null
            width: 100
        name: Inhoud
        uid: b540975d-1dc3-4af5-954d-fc00ccff89f6
        userCondition: null
fs: assets
handle: images
name: Images
sortOrder: 1
subpath: images
titleTranslationKeyFormat: null
titleTranslationMethod: language
transformFs: ''
transformSubpath: images
