isPublic: false
name: local
scope:
  - 'sites.c074f890-9562-4809-b6a5-9905399f1210:read'
  - 'sites.089632a9-4660-4bdc-a011-d5dcfed12764:read'
  - 'sites.d13359bc-448f-48e7-9263-72b92ed81002:read'
  - 'sites.66aa3aba-35c5-4d21-93aa-ebcb50421172:read'
  - 'sections.cac2fb52-fcc3-4293-9eb4-9f4e0a4fb976:read'
  - 'sections.90024d10-4964-4e23-888f-56257206b34a:read'
  - 'sections.21f7a7cb-63f7-437d-9916-29fa90e4806c:read'
  - 'sections.3cc34c47-0437-4db7-9421-2ed23074c150:read'
  - 'sections.4d8b0e31-4e96-494b-9bb5-21716396ffaf:read'
  - 'sections.a8fcf29d-38ca-4ca0-b71f-4de9e9cff085:read'
  - 'sections.e3b758a0-7052-4bdf-8096-2f0a5fd0e7b4:read'
  - 'sections.8c94fbd9-93e4-4119-8855-65472236e26d:read'
  - 'sections.ca1fbf65-ce9d-46f8-a1ae-1985ad4ed862:read'
  - 'sections.5523e7e2-d128-458c-b28a-3c9fcfb63554:read'
  - 'sections.3203131b-63df-45fa-890b-ef360562dc8f:read'
  - 'sections.a8b7d154-c5db-4e66-9a2e-b5dd891b7263:read'
  - 'sections.6a32efc3-dd82-4540-9099-f19140cd9e70:read'
  - 'sections.c7b2399b-e1e1-4439-aa77-d5ee7f57f8b0:read'
  - 'sections.1aea4e3e-1614-4e7a-b6a3-a30723cdd178:read'
  - 'sections.f2b5ea7f-5c01-4106-9305-85559361a2a7:read'
  - 'sections.ac5bde49-c71b-4edf-847e-550fb87d2619:read'
  - 'sections.b235ef4f-65f2-40df-b3ab-362721465a76:read'
  - 'sections.5da9fddb-7db3-4ab7-a475-8efb5e3683c6:read'
  - 'sections.383e56a9-8a89-48b4-af80-8e69c8979acd:read'
  - 'sections.6185acf9-3abb-4565-ad05-f1e327e1dd15:read'
  - 'sections.ea4bf2b8-690e-4f4b-acd9-5e7022a66761:read'
  - 'sections.877ea780-7596-469e-8785-fb595903d3e9:read'
  - 'sections.0726a991-151f-48ab-ba6f-ba586c1a4523:read'
  - 'sections.93a53679-ae1a-42ab-a3e2-a5f4aa8774d7:read'
  - 'sections.0c22beff-051e-4628-9398-939d97327358:read'
  - 'nestedentryfields.bdadc13b-5397-44dc-9d8b-7f74bc739f86:read'
  - 'nestedentryfields.85b15669-83a3-4743-b1db-4b79eb231048:read'
  - 'nestedentryfields.a6e914a2-6a89-4bfd-8f3f-aabf1f31e67b:read'
  - 'nestedentryfields.b0817961-2428-4368-b968-f98e6116bd03:read'
  - 'nestedentryfields.c597df25-6a4c-4ce1-a443-709db0448b92:read'
  - 'nestedentryfields.32002598-7728-4547-8fa7-171d7951c7f5:read'
  - 'nestedentryfields.ea93d46f-8749-4505-b97a-5be1e9a05da9:read'
  - 'nestedentryfields.764092b6-1005-45cc-9ec9-10b7d33a4438:read'
  - 'nestedentryfields.899a4482-9042-4c04-bc03-0b07b84211e4:read'
  - 'volumes.b897d70e-3e6f-4843-92e1-0f0321d65afd:read'
  - 'categorygroups.945ee420-b73c-4781-9c48-0eb9ef980739:read'
  - 'categorygroups.d333897b-91df-4986-b344-ffbb7e7a7231:read'
  - 'categorygroups.2f99b91e-a36f-413c-a2b8-79fe072c9c24:read'
  - 'taggroups.8c20f210-c445-48bb-b386-d163a9767ac0:read'
