columnSuffix: null
handle: background
instructions: null
name: Achtergrond
searchable: false
settings:
  customOptions: false
  options:
    -
      __assoc__:
        -
          - label
          - wit
        -
          - value
          - white
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - cyaan
        -
          - value
          - cyan
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - geel
        -
          - value
          - yellow
        -
          - icon
          - ''
        -
          - color
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\Dropdown
