columnSuffix: null
handle: isHighlighted
instructions: null
name: Highlight
searchable: false
settings:
  default: false
  offLabel: Nee
  onLabel: Ja
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
