columnSuffix: null
handle: json
instructions: null
name: JSON
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: true
  initialRows: 10
  multiline: true
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
