columnSuffix: null
handle: metaDescription
instructions: null
name: 'Pagina beschrijving'
searchable: true
settings:
  byteLimit: null
  charLimit: 255
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: enlarged
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
