columnSuffix: null
handle: metaTitle
instructions: null
name: 'Pagina titel'
searchable: true
settings:
  byteLimit: null
  charLimit: 150
  code: false
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: language
type: craft\fields\PlainText
