columnSuffix: null
handle: richText
instructions: null
name: 'Rich Text'
searchable: true
settings:
  availableTransforms: ''
  availableVolumes: ''
  ckeConfig: 2e215599-0c9c-4f66-9558-cd1cd655151a
  createButtonLabel: null
  defaultTransform: null
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups: '*'
  wordLimit: null
translationKeyFormat: null
translationMethod: language
type: craft\ckeditor\Field
