columnSuffix: null
handle: source
instructions: null
name: 'Energy source'
searchable: true
settings:
  allowSelfRelations: false
  branchLimit: null
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  selectionLabel: 'Add category'
  showCardsInGrid: false
  showSiteMenu: false
  source: 'group:d333897b-91df-4986-b344-ffbb7e7a7231'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Categories
