columnSuffix: null
handle: stretchChildren
instructions: null
name: 'Stretch children'
searchable: false
settings:
  default: false
  offLabel: null
  onLabel: null
translationKeyFormat: null
translationMethod: none
type: craft\fields\Lightswitch
