defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 95359c32-8f2c-4c6d-a0c7-842400ab3a65
handle: NAVIGATION
maxAuthors: 1
name: Navigation
propagationMethod: none
siteSettings:
  66aa3aba-35c5-4d21-93aa-ebcb50421172:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  089632a9-4660-4bdc-a011-d5dcfed12764:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  c074f890-9562-4809-b6a5-9905399f1210:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  d13359bc-448f-48e7-9263-72b92ed81002:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: null
  uid: b3a2aeba-09f2-4a14-b845-ece799ce015f
type: structure
