defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 25d26794-2f4f-4a4c-a324-5109b4870342
handle: PRODUCTION_OVERVIEW
maxAuthors: 1
name: 'NED - Productiedata'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - refresh
        - '1'
      -
        - urlFormat
        - '{url}'
propagationMethod: all
siteSettings:
  66aa3aba-35c5-4d21-93aa-ebcb50421172:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: en/production
  d13359bc-448f-48e7-9263-72b92ed81002:
    enabledByDefault: true
    hasUrls: true
    template: null
    uriFormat: nl/productie
type: single
