defaultPlacement: end
enableVersioning: false
entryTypes:
  -
    uid: 54f8b5fb-9b68-4a82-940c-371b8c89f301
handle: TOOLTIPS
maxAuthors: 1
name: Tooltips
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primaire invoer-pagina'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: siteGroup
siteSettings:
  66aa3aba-35c5-4d21-93aa-ebcb50421172:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  089632a9-4660-4bdc-a011-d5dcfed12764:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  c074f890-9562-4809-b6a5-9905399f1210:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
  d13359bc-448f-48e7-9263-72b92ed81002:
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
structure:
  maxLevels: 1
  uid: 573942ec-1ec1-43d8-aaf6-0ee76a03fbc9
type: structure
