tabs:
  -
    elementCondition: null
    elements:
      -
        autocapitalize: true
        autocomplete: false
        autocorrect: true
        class: null
        dateAdded: '2025-09-18T15:35:57+02:00'
        disabled: false
        elementCondition: null
        id: null
        includeInCards: false
        inputType: null
        instructions: null
        label: null
        max: null
        min: null
        name: null
        orientation: null
        placeholder: null
        providesThumbs: false
        readonly: false
        requirable: false
        size: null
        step: null
        tip: null
        title: null
        type: craft\fieldlayoutelements\addresses\LabelField
        uid: 0f6ee6a7-1e57-4be9-9e02-09016fee3c54
        userCondition: null
        warning: null
        width: 100
      -
        attribute: countryCode
        dateAdded: '2025-09-18T15:35:57+02:00'
        elementCondition: null
        id: null
        includeInCards: false
        instructions: null
        label: null
        orientation: null
        providesThumbs: false
        requirable: false
        tip: null
        type: craft\fieldlayoutelements\addresses\CountryCodeField
        uid: bd4a0b6d-75c3-4749-8290-3b8b3cd719dc
        userCondition: null
        warning: null
        width: 100
      -
        dateAdded: '2025-09-18T15:35:57+02:00'
        elementCondition: null
        includeInCards: true
        instructions: null
        label: null
        providesThumbs: false
        required: false
        tip: null
        type: craft\fieldlayoutelements\addresses\AddressField
        uid: a3a121e6-04d3-4cca-8c35-c821cc1ea340
        userCondition: null
        warning: null
    name: Content
    uid: e86769e3-015b-4799-ac9e-587ca58daf39
    userCondition: null
